name: Node CI

on:
  push:
    branches: master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm run lint
        env:
          CI: true
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_PAGES_TOKEN }}
          publish_branch: gh-pages # The branch the action should deploy to.
          publish_dir: build # The folder the action should deploy.
